version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacientes_db
    ports:
      - "3306:3306"
    networks:
      - microservices-net

  config-server:
    build: ./microservice-config
    ports:
      - "8888:8888"
    networks:
      - microservices-net

  eureka-server:
    build: ./microservice-eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    depends_on:
      - config-server

  gateway-server:
    build: ./microservice-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - eureka-server

  paciente-service:
    build: ./microservice-paciente
    ports:
      - "8090:8090"
    networks:
      - microservices-net
    depends_on:
      - mysql
      - config-server
      - eureka-server

networks:
  microservices-net:
    driver: bridge
