server:
  port: 8090

spring:
  application:
    name: msvc-paciente
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://mysql-db:3306/pacientes_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
