server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: paciente-service
          uri: lb://msvc-paciente
          predicates:
            - Path=/api/pacientes/**
